import moment from 'moment';
const initialPatientState = {
  lastname: '',
  firstname: '',
  patronymic: '',
  birthday: '',
  gender: 'unspecified',
  description: '',
  phone: '',
  email: '',
  policy: '',
  medicalinsurancecompany: '',
  snils: '',
  inn: '',
  typedocId: 1,
  series: '',
  number: '',
  dateissued: '',
  whoissued: '',
  regionId: 70,
  city: '',
  district: '',
  locality: '',
  street: '',
  house: '',
  apartment: '',
  index: '',
  school: '',
  disability: '',
  blood: '',
  allergy: '',
  published: true,
};
const initialParentState = {
  lastname: '',
  firstname: '',
  patronymic: '',
  parentnow: true,
  birthday: '',
  gender: 'unspecified',
  kinship: '',
  kinshipdocument: '',
  phone: '',
  email: '',
  policy: '',
  medicalinsurancecompany: '',
  snils: '',
  inn: '',
  typedocId: 1,
  series: '',
  number: '',
  dateissued: '',
  whoissued: '',
  regionId: 70,
  city: '',
  district: '',
  locality: '',
  street: '',
  house: '',
  apartment: '',
  index: '',
  family: '',
  training: '',
  busyness: '',
  job: '',
  blood: '',
  published: true,
};
const initialCallingState = {
  date: moment().format('YYYY-MM-DD'),
  datecall: moment().format('YYYY-MM-DD'),
  timestart: moment().format('HH:mm'),
  timeend: moment().format('HH:mm'),
  description: '',
};
const initialContractState = {
  datestart: moment().format('YYYY-MM-DD'),
  dateend: moment().format('YYYY-MM-DD'),
  description: '',
};
const initialPricetState = {
  name: '',
  price: '',
  published: true,
};
const initialSpecialState = {
  name: '',
  description: '',
  published: true,
};
const initialUserState = {
  lastname: '',
  firstname: '',
  patronymic: '',
  birthday: '',
  phone: '',
  snils: '',
  inn: '',
  description: '',
  showinschedule: true,
  published: true,
  accessToSystem: false,
};
const initialPofileState = {
  email: '',
  password: '',
  roleId: '',
};
const streetLists = ['Улица', 'Проспект', 'Площадь', 'Переулок'];
export {
  initialPatientState,
  initialParentState,
  initialCallingState,
  streetLists,
  initialContractState,
  initialPricetState,
  initialSpecialState,
  initialUserState,
  initialPofileState,
};
